name: Build and Release SDK

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install

      - name: Build SDK
        run: pnpm sdk:build

      - name: Package SDK (pnpm pack)
        run: |
          cd packages/sdk
          pnpm pack
          mv *.tgz ../../lilysilk-pay-sdk-web-${{ github.ref_name }}.tgz

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            lilysilk-pay-sdk-web-${{ github.ref_name }}.tgz
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
